### ISSUE TITLE
How about generators?

### ISSUE THREAD

**Issue by stefanos82** [morozovsk/php-arrays-in-memory-comparison#3]
Is there a particular reason you did not use generators?

It could reduce your whole memory consumption to a whole new level.

![image](https://user-images.githubusercontent.com/1777466/77963275-c4059980-72e5-11ea-8862-01220a9c5e99.png)

**Comment by morozovsk** [comment]
Generators are good for one run. In my app I needed to load data into memory from disk only once and then make 1000 requests per second while 15 minutes.
